application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
      default: step-autocert
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
      default: step
  IMAGE_STEP:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  STEP_SERVICE_ACCOUNT:
    type: string
    title: Step Service Account
    description: Service account to assign to main Step resources
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_STEP
- STEP_SERVICE_ACCOUNT